"""add ssh key support to git credentials

Revision ID: 20250914_add_ssh_key_support_to_git_credentials
Revises: 
Create Date: 2025-09-14 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = '20250914_add_ssh_key_support_to_git_credentials'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查列是否已存在
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns('git_credentials')]
    
    with op.batch_alter_table('git_credentials', schema=None) as batch_op:
        if 'encrypted_ssh_key' not in columns:
            batch_op.add_column(sa.Column('encrypted_ssh_key', sa.Text(), nullable=True))
        if 'ssh_key_fingerprint' not in columns:
            batch_op.add_column(sa.Column('ssh_key_fingerprint', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查列是否存在
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns('git_credentials')]
    
    with op.batch_alter_table('git_credentials', schema=None) as batch_op:
        if 'ssh_key_fingerprint' in columns:
            batch_op.drop_column('ssh_key_fingerprint')
        if 'encrypted_ssh_key' in columns:
            batch_op.drop_column('encrypted_ssh_key')

    # ### end Alembic commands ###