"""Add physical host and container info to nodes

Revision ID: 72ab59438695
Revises: 5ec180ed57c0
Create Date: 2025-09-15 23:28:38.295874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72ab59438695'
down_revision: Union[str, Sequence[str], None] = '5ec180ed57c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cp_task_target_nodes')
    op.add_column('cp_nodes', sa.Column('physical_host_id', sa.String(length=100), nullable=True, comment='物理主机标识（如MAC地址）'))
    op.add_column('cp_nodes', sa.Column('physical_host_name', sa.String(length=100), nullable=True, comment='物理主机名'))
    op.add_column('cp_nodes', sa.Column('container_id', sa.String(length=100), nullable=True, comment='容器ID（如果是Docker容器）'))
    op.add_column('cp_nodes', sa.Column('instance_name', sa.String(length=100), nullable=True, comment='实例名称（用户自定义）'))
    op.alter_column('cp_nodes', 'tags',
               existing_type=mysql.VARCHAR(length=100),
               comment='节点标签，如 gpu,proxy,chrome',
               existing_comment='节点标签，如 gpu,proxy',
               existing_nullable=True)
    op.alter_column('cp_nodes', 'capabilities',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_comment="节点能力（JSON 格式），如 {'gpu': true, 'browser': 'chrome'}",
               existing_nullable=True)
    op.alter_column('cp_tasks', 'last_run_status',
               existing_type=mysql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE'),
               type_=sa.String(length=20),
               existing_comment='最近一次执行状态',
               existing_nullable=True)
    op.alter_column('cp_tasks', 'distribution_mode',
               existing_type=mysql.ENUM('ANY', 'SPECIFIC', 'MULTIPLE', 'TAG_BASED'),
               nullable=False,
               existing_comment='任务分发模式')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cp_tasks', 'distribution_mode',
               existing_type=mysql.ENUM('ANY', 'SPECIFIC', 'MULTIPLE', 'TAG_BASED'),
               nullable=True,
               existing_comment='任务分发模式')
    op.alter_column('cp_tasks', 'last_run_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE'),
               existing_comment='最近一次执行状态',
               existing_nullable=True)
    op.alter_column('cp_nodes', 'capabilities',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_comment="节点能力（JSON 格式），如 {'gpu': true, 'browser': 'chrome'}",
               existing_nullable=True)
    op.alter_column('cp_nodes', 'tags',
               existing_type=mysql.VARCHAR(length=100),
               comment='节点标签，如 gpu,proxy',
               existing_comment='节点标签，如 gpu,proxy,chrome',
               existing_nullable=True)
    op.drop_column('cp_nodes', 'instance_name')
    op.drop_column('cp_nodes', 'container_id')
    op.drop_column('cp_nodes', 'physical_host_name')
    op.drop_column('cp_nodes', 'physical_host_id')
    op.create_table('cp_task_target_nodes',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['cp_nodes.id'], name=op.f('cp_task_target_nodes_ibfk_1')),
    sa.ForeignKeyConstraint(['task_id'], ['cp_tasks.id'], name=op.f('cp_task_target_nodes_ibfk_2')),
    sa.PrimaryKeyConstraint('task_id', 'node_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
