"""add_git_credentials_table

Revision ID: 7b01d2f1cd2d
Revises: b12497496745
Create Date: 2025-09-14 09:09:06.704082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b01d2f1cd2d'
down_revision: Union[str, Sequence[str], None] = 'b12497496745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_credentials_id'), 'git_credentials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_credentials_id'), table_name='git_credentials')
    op.drop_table('git_credentials')
    # ### end Alembic commands ###
